Civil-Service-Human-Resources/lpg-report-service

src/main/java/uk/gov/cshr/report/domain/learnerrecord/Booking.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/BookingReportRow.java

- Added confirmationTime, cancellationTime, accessibilityOptions and cancellation reason to **Booking.java** and **BookingReportRow.java**
- Set new parameters in **ReportRowFactory.java**

LPFG-1186-MI-Accesability-Options

---

src/main/java/uk/gov/cshr/report/domain/catalogue/Course.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/BookingReportRow.java
src/main/java/uk/gov/cshr/report/reports/ModuleReportRow.java

Adds a topicId to course.
- Added topicId to **Course.java**
- Set topicId in **ReportRowFactory.java**
- Added courseTopicID to **ModuleReportRow.java**

LPFG-1198 Topic Id

---

src/main/java/uk/gov/cshr/report/domain/learnerrecord/Booking.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/BookingReportRow.java

- adding booking po numbers to booking report

LC-137: adding po to report

---

src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/test/java/uk/gov/cshr/report/factory/ReportRowFactoryTest.java

- get email from booking instead of id

LC-164: get email from bookings

---

src/main/java/uk/gov/cshr/report/domain/identity/Identity.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/service/IdentityService.java
src/main/java/uk/gov/cshr/report/service/ParameterizedTypeReferenceFactory.java
src/main/java/uk/gov/cshr/report/service/ReportService.java
src/main/resources/application.yml
src/test/java/uk/gov/cshr/report/factory/ReportRowFactoryTest.java
src/test/java/uk/gov/cshr/report/service/ReportServiceTest.java

- handle modules if they don't exist in catalogue

LC-180: handling null modules

---

src/main/java/uk/gov/cshr/report/controller/BookingController.java
src/main/java/uk/gov/cshr/report/controller/ModuleController.java
src/main/java/uk/gov/cshr/report/domain/registry/CivilServant.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/BookingReportRow.java
src/main/java/uk/gov/cshr/report/reports/ModuleReportRow.java
src/main/java/uk/gov/cshr/report/service/ReportService.java
src/test/java/uk/gov/cshr/report/controller/BookingControllerTest.java
src/test/java/uk/gov/cshr/report/controller/ModuleControllerTest.java
src/test/java/uk/gov/cshr/report/factory/ReportRowFactoryTest.java
src/test/java/uk/gov/cshr/report/service/ReportServiceTest.java

fix-supplier-modules-report

---

src/main/java/uk/gov/cshr/report/domain/learnerrecord/ModuleRecord.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/ModuleReportRow.java
src/test/java/uk/gov/cshr/report/controller/ModuleControllerTest.java
src/test/java/uk/gov/cshr/report/factory/ReportRowFactoryTest.java

- adding updated/completed columns

Lc 221 updated completed cols

---

src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java

- get email from id not booking

LPFG-1130-change-my-email-v2

---

Dockerfile
build.gradle
lib/AI-Agent.xml
src/main/resources/ApplicationInsights.xml

enable Azure Application Insights

---

src/main/java/uk/gov/cshr/report/domain/LearnerRecordEvent.java
src/main/java/uk/gov/cshr/report/domain/catalogue/Event.java
src/main/java/uk/gov/cshr/report/domain/learnerrecord/Booking.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/BookingReportRow.java
src/main/java/uk/gov/cshr/report/reports/ModuleReportRow.java

**Jira Ticket:** 
https://cshrdigitalandanalysis.atlassian.net/browse/LC-280
https://cshrdigitalandanalysis.atlassian.net/browse/LC-309
This branch adds booking reference, event location, event ID and event date. 
This branch is relying on these two branches: 
https://github.com/Civil-Service-Human-Resources/lpg-learner-record/pull/107
https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/121

Displaying Booking reference on the MI report

---

src/main/java/uk/gov/cshr/report/domain/LearnerRecordEvent.java
src/main/java/uk/gov/cshr/report/domain/catalogue/Event.java
src/main/java/uk/gov/cshr/report/domain/learnerrecord/Booking.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/BookingReportRow.java

Release branch for f2f features
Contains PR:
https://github.com/Civil-Service-Human-Resources/lpg-report-service/pull/26
https://github.com/Civil-Service-Human-Resources/lpg-report-service/pull/28

Releases f2f features

---

src/main/java/uk/gov/cshr/report/repository/DbRepository.java

Implemented fix

---

src/main/java/uk/gov/cshr/report/controller/BookingController.java
src/main/java/uk/gov/cshr/report/controller/ModuleController.java

Each request for report will log info about which user performs the report request and what date range is being passed.

Implemented logging

---

src/main/java/uk/gov/cshr/report/controller/ModuleController.java
src/main/java/uk/gov/cshr/report/domain/learnerrecord/ModuleRecord.java
src/main/java/uk/gov/cshr/report/factory/ReportRowFactory.java
src/main/java/uk/gov/cshr/report/reports/ModuleReportRow.java
src/main/java/uk/gov/cshr/report/service/IdentityService.java
src/main/java/uk/gov/cshr/report/service/LearnerRecordService.java
src/main/java/uk/gov/cshr/report/service/LearningCatalogueService.java
src/main/java/uk/gov/cshr/report/service/ReportService.java
src/main/resources/application.yml
src/test/java/uk/gov/cshr/report/factory/ReportRowFactoryTest.java
src/test/java/uk/gov/cshr/report/service/LearnerRecordServiceTest.java
src/test/java/uk/gov/cshr/report/service/LearningCatalogueServiceTest.java
src/test/java/uk/gov/cshr/report/service/ReportServiceTest.java

idt-feature-LC-451 module mi report logic improvement

idt-feature-LC-451 module mi report logic improvement

---

src/main/java/uk/gov/cshr/report/controller/HealthController.java

This change creates a `/health` endpoint used for health checks

Add healthcheck endpoint

---

.gitignore
docker-compose.yml
pom.xml
src/main/java/uk/gov/cshr/report/Application.java
src/main/java/uk/gov/cshr/report/config/AppConfig.java
src/main/java/uk/gov/cshr/report/config/partitionManager/PartitionManagerConfiguration.java
src/main/java/uk/gov/cshr/report/config/partitionManager/PartitionManagerProperties.java
src/main/java/uk/gov/cshr/report/repository/databaseManager/DatabaseManager.java
src/main/java/uk/gov/cshr/report/repository/databaseManager/DatabaseSqlHelper.java
src/main/java/uk/gov/cshr/report/repository/databaseManager/IDatabaseSqlHelper.java
src/main/java/uk/gov/cshr/report/service/PartitionManager.java
src/main/resources/application.yml
src/main/resources/db/migration/postgresql/V1__init.sql
src/test/java/uk/gov/cshr/report/integration/CustomPGContainer.java
src/test/java/uk/gov/cshr/report/integration/DatabaseManagerIntegrationTest.java
src/test/java/uk/gov/cshr/report/integration/IntegrationTestBase.java
src/test/java/uk/gov/cshr/report/repository/DatabaseManagerTest.java
src/test/java/uk/gov/cshr/report/repository/DatabaseSqlHelperTest.java
src/test/java/uk/gov/cshr/report/service/PartitionManagerTest.java
src/test/resources/application-no-partition-manager.properties

- Introduce new postgres database connection
- New `coursecompletions` table for storing course completion data
- Partition manager code for creating partitions of the new table
- Integration tests using TectContainers

LC 2777 reporting database

---

pom.xml
src/main/java/uk/gov/cshr/report/config/ClockConfig.java
src/main/java/uk/gov/cshr/report/config/CustomBasicAuthenticationProvider.java
src/main/java/uk/gov/cshr/report/config/OpenApiConfig.java
src/main/java/uk/gov/cshr/report/config/SecurityConfig.java
src/main/java/uk/gov/cshr/report/controller/ApiExceptionHandler.java
src/main/java/uk/gov/cshr/report/controller/BookingController.java
src/main/java/uk/gov/cshr/report/controller/CourseCompletionsController.java
src/main/java/uk/gov/cshr/report/controller/model/AggregationBinDelimiter.java
src/main/java/uk/gov/cshr/report/controller/model/AggregationResponse.java
src/main/java/uk/gov/cshr/report/controller/model/ErrorDto.java
src/main/java/uk/gov/cshr/report/controller/model/ErrorDtoFactory.java
src/main/java/uk/gov/cshr/report/controller/model/GetCourseCompletionsParams.java
src/main/java/uk/gov/cshr/report/domain/CourseCompletionEvent.java
src/main/java/uk/gov/cshr/report/domain/aggregation/Aggregation.java
src/main/java/uk/gov/cshr/report/repository/CourseCompletionEventRepository.java
src/main/java/uk/gov/cshr/report/repository/databaseManager/DatabaseManager.java
src/main/java/uk/gov/cshr/report/service/CourseCompletionService.java
src/main/resources/application.yml
src/test/java/uk/gov/cshr/report/configuration/TestConfig.java
src/test/java/uk/gov/cshr/report/controller/BookingControllerTest.java
src/test/java/uk/gov/cshr/report/controller/CourseCompletionsControllerTest.java
src/test/java/uk/gov/cshr/report/controller/ModuleControllerTest.java
src/test/java/uk/gov/cshr/report/integration/CourseCompletionsIntegrationTest.java
src/test/java/uk/gov/cshr/report/repository/CourseCompletionEventRepositoryTest.java
src/test/java/uk/gov/cshr/report/repository/DatabaseManagerTest.java
src/test/resources/db/migration/postgresql/V1.1__course_completions_data.sql

- `GET /course-completions/aggregations/by-course` endpoint. This is to aggregate course completions by specific course/organisation IDs
- Add swagger
- Refactor spring security

LC-2699 Course completions aggregations endpoint

---

src/main/java/uk/gov/cshr/report/controller/CourseCompletionsController.java
src/main/java/uk/gov/cshr/report/controller/mappers/PostCourseCompletionsReportRequestsParamsToReportRequestMapper.java
src/main/java/uk/gov/cshr/report/controller/model/GetCourseCompletionReportRequestsResponse.java
src/main/java/uk/gov/cshr/report/domain/CourseCompletionEvent.java
src/main/java/uk/gov/cshr/report/domain/report/CourseCompletionCsv.java
src/main/java/uk/gov/cshr/report/domain/report/CourseCompletionReportRequest.java
src/main/java/uk/gov/cshr/report/domain/report/CourseCompletionReportRequestStatus.java
src/main/java/uk/gov/cshr/report/domain/report/CustomColumnPositionStrategy.java
src/main/java/uk/gov/cshr/report/repository/CourseCompletionReportRequestRepository.java
src/main/java/uk/gov/cshr/report/service/CourseCompletionReportRequestService.java
src/main/java/uk/gov/cshr/report/service/CourseCompletionsCsvService.java
src/main/java/uk/gov/cshr/report/service/Scheduler.java
src/main/java/uk/gov/cshr/report/service/messaging/coursecompletions/CourseCompletionMessage.java
src/main/java/uk/gov/cshr/report/service/messaging/coursecompletions/CourseCompletionsMessageConverter.java
src/main/resources/db/migration/postgresql/V2.4__amend-course-completion-event-columns.sql
src/test/java/uk/gov/cshr/report/integration/CourseCompletionsReportRequestIntegrationTest.java

- Rename org abbreviation column to organisation name
- Rename grade code column to grade name
- Fix ordering on course completions CSV
- Remove extra CSV fields

LC 3162 update columns

---

src/main/java/uk/gov/cshr/report/client/identity/IdentitiesClient.java
src/main/java/uk/gov/cshr/report/client/learnerRecord/LearnerRecordClient.java
src/main/java/uk/gov/cshr/report/client/learningCatalogue/ILearningCatalogueClient.java
src/main/java/uk/gov/cshr/report/client/learningCatalogue/LearningCatalogueClient.java
src/main/java/uk/gov/cshr/report/domain/learnerrecord/FromToParamsCourseIds.java
src/main/java/uk/gov/cshr/report/domain/learnerrecord/FromToParamsUserIds.java
src/main/java/uk/gov/cshr/report/service/LearnerRecordService.java
src/main/java/uk/gov/cshr/report/service/LearningCatalogueService.java
src/main/java/uk/gov/cshr/report/service/ReportService.java
src/main/java/uk/gov/cshr/report/service/util/HttpUtils.java
src/main/resources/application.yml
src/test/java/uk/gov/cshr/report/service/LearnerRecordServiceTest.java
src/test/java/uk/gov/cshr/report/service/ReportServiceTest.java

- Implement POST requests for module record reports
- Optimise existing batched API requests for legacy reports

LC-3532 optimise reports

---

src/main/java/uk/gov/cshr/report/repository/RegisteredLearnerRepository.java
src/main/java/uk/gov/cshr/report/service/RegisteredLearnersService.java
src/main/java/uk/gov/cshr/report/service/messaging/registeredlearners/RegisteredLearnerAccountActivateService.java
src/main/java/uk/gov/cshr/report/service/messaging/registeredlearners/RegisteredLearnerEmailUpdateService.java
src/main/java/uk/gov/cshr/report/service/messaging/registeredlearners/models/RegisteredLearnerDataType.java
src/main/java/uk/gov/cshr/report/service/messaging/registeredlearners/models/RegisteredLearnerEmailUpdate.java
src/main/java/uk/gov/cshr/report/service/messaging/registeredlearners/models/RegisteredLearnerEmailUpdateMessage.java
src/main/java/uk/gov/cshr/report/service/messaging/registeredlearners/models/RegisteredLearnerEmailUpdateMessageMetadata.java
src/test/java/uk/gov/cshr/report/messaging/RegisteredLearnersMessagingTest.java
src/test/java/uk/gov/cshr/report/service/messaging/registeredlearners/RegisteredLearnerEmailUpdateServiceTest.java

Testing Document:
https://cshrdigitalandanalysis.atlassian.net/wiki/spaces/LPG/pages/3955392513/LC-3560+Amend+the+learner+s+email+update+process+to+update+the+Registered+Learners+Report+data

LC-3560 - Amend learner email update process to update registered learners report data

---

src/main/java/uk/gov/cshr/report/repository/RegisteredLearnerRepository.java
src/test/java/uk/gov/cshr/report/messaging/RegisteredLearnersMessagingTest.java

Setting Organisation as null when email is updated

LC-3560-Set Org Null on Email Update
